In [1]:
import sys 
sys.path.append('../')

In [2]:
from src.utils.find_ticker import find_ticker_finnhub
from src.utils.get_company_overview import get_company_overview
from src.utils.get_stock_alphavantage import get_stock_quote_alphavantage
from src.connect import create_table_from_dataframe 
from src.connect import insert_dataframe
from src.clean_supabase_data import clean_column_names
from src.clean_supabase_data import normalize_columns

In [3]:
# api key 
import os 
finnhub_api_key = os.getenv("FINNHUB_API_KEY")
alpha_api_key = os.getenv("ALPHA_API_KEY")

In [4]:
company_name = "Apple"
ticker = find_ticker_finnhub(company_name,finnhub_api_key)
company_overview_json = get_company_overview(ticker,alpha_api_key)
company_stock = get_stock_quote_alphavantage(ticker,alpha_api_key)

In [5]:
ticker

'AAPL'

In [6]:
company_overview_json

{'Symbol': 'AAPL',
 'AssetType': 'Common Stock',
 'Name': 'Apple Inc',
 'Description': "Apple Inc. is an American multinational technology company that specializes in consumer electronics, computer software, and online services. Apple is the world's largest technology company by revenue (totalling $274.5 billion in 2020) and, since January 2021, the world's most valuable company. As of 2021, Apple is the world's fourth-largest PC vendor by unit sales, and fourth-largest smartphone manufacturer. It is one of the Big Five American information technology companies, along with Amazon, Google, Microsoft, and Facebook.",
 'CIK': '320193',
 'Exchange': 'NASDAQ',
 'Currency': 'USD',
 'Country': 'USA',
 'Sector': 'TECHNOLOGY',
 'Industry': 'ELECTRONIC COMPUTERS',
 'Address': 'ONE INFINITE LOOP, CUPERTINO, CA, US',
 'OfficialSite': 'https://www.apple.com',
 'FiscalYearEnd': 'September',
 'LatestQuarter': '2025-03-31',
 'MarketCapitalization': '3192676418000',
 'EBITDA': '138866000000',
 'PERatio': '33.3',
 'PEGRatio': '1.997',
 'BookValue': '4.471',
 'DividendPerShare': '1',
 'DividendYield': '0.0047',
 'EPS': '6.42',
 'RevenuePerShareTTM': '26.45',
 'ProfitMargin': '0.243',
 'OperatingMarginTTM': '0.31',
 'ReturnOnAssetsTTM': '0.238',
 'ReturnOnEquityTTM': '1.38',
 'RevenueTTM': '400366010000',
 'GrossProfitTTM': '186699006000',
 'DilutedEPSTTM': '6.42',
 'QuarterlyEarningsGrowthYOY': '0.078',
 'QuarterlyRevenueGrowthYOY': '0.051',
 'AnalystTargetPrice': '229.87',
 'AnalystRatingStrongBuy': '6',
 'AnalystRatingBuy': '20',
 'AnalystRatingHold': '17',
 'AnalystRatingSell': '2',
 'AnalystRatingStrongSell': '1',
 'TrailingPE': '33.3',
 'ForwardPE': '27.47',
 'PriceToSalesRatioTTM': '7.97',
 'PriceToBookRatio': '47.88',
 'EVToRevenue': '8.11',
 'EVToEBITDA': '23.39',
 'Beta': '1.199',
 '52WeekHigh': '259.47',
 '52WeekLow': '168.99',
 '50DayMovingAverage': '205.39',
 '200DayMovingAverage': '222.09',
 'SharesOutstanding': '14935800000',
 'SharesFloat': '14911331000',
 'PercentInsiders': '2.085',
 'PercentInstitutions': '62.869',
 'DividendDate': '2025-05-15',
 'ExDividendDate': '2025-05-12'}

In [7]:
company_stock

{'ticker': 'AAPL',
 'open': '214.7000',
 'high': '215.2400',
 'low': '213.4000',
 'price': '213.8800',
 'volume': '40268781',
 'latest_trading_day': '2025-07-25',
 'previous_close': '213.7600',
 'change': '0.1200',
 'change_percent': '0.0561%'}

In [8]:
import pandas as pd 
company_overview_data = pd.DataFrame([company_overview_json],columns=company_overview_json.keys())

In [9]:
company_stock_data = pd.DataFrame([company_stock],columns=company_stock.keys())

In [10]:
company_stock_data.head()

  ticker      open      high  ... previous_close  change change_percent
0   AAPL  214.7000  215.2400  ...       213.7600  0.1200        0.0561%

[1 rows x 10 columns]

In [11]:
company_overview_data.head()

  Symbol     AssetType  ... DividendDate ExDividendDate
0   AAPL  Common Stock  ...   2025-05-15     2025-05-12

[1 rows x 55 columns]

In [12]:
company_overview_data = company_overview_data.rename(columns={"Symbol":"ticker"})

In [13]:
company_overview_data

  ticker     AssetType  ... DividendDate ExDividendDate
0   AAPL  Common Stock  ...   2025-05-15     2025-05-12

[1 rows x 55 columns]

In [14]:
final_data = company_overview_data.merge(company_stock_data,on='ticker',how='left')

In [15]:
final_data

  ticker     AssetType       Name  ... previous_close  change change_percent
0   AAPL  Common Stock  Apple Inc  ...       213.7600  0.1200        0.0561%

[1 rows x 64 columns]

In [17]:
final_data_clean = clean_column_names(final_data)
final_data_clean = normalize_columns(final_data_clean)
create_table_from_dataframe(final_data_clean,table_name="finadata")
insert_dataframe(final_data_clean,table_name='finadata')

1 lignes insérées dans finadata.

In [18]:
query = f"""

SELECT * 
FROM finadata 

"""

from src.connect import run_query

result_df = run_query(query,params=None)

In [19]:
result_df

  ticker     assettype       name  ... previous_close  change change_percent
0   AAPL  Common Stock  Apple Inc  ...       213.7600  0.1200        0.0561%

[1 rows x 64 columns]