In [1]:
import sys
import os
import yaml

sys.path.append("..")

with open("../config.yaml", "r") as f:
    config = yaml.safe_load(f)

feature_store_path = config["feature_store_path"]
print("Feature store path:", feature_store_path)

from src.connect import fetch_feature, run_query

Feature store path: C:\Users\o\forcasting\walmart_forcasting\feature_store

In [2]:

query = f"""

SELECT m."Store", m."Date"
FROM walmart AS m

"""
portfolio = run_query(query)

In [3]:
portfolio

      Store        Date
0         1  05-02-2010
1         1  12-02-2010
2         1  19-02-2010
3         1  26-02-2010
4         1  05-03-2010
...     ...         ...
6430     45  28-09-2012
6431     45  05-10-2012
6432     45  12-10-2012
6433     45  19-10-2012
6434     45  26-10-2012

[6435 rows x 2 columns]

In [4]:
data = fetch_feature("growth_features.sql",portfolio=portfolio)

In [5]:
data

,store,date,Weekly_Sales,weekly_sales_diff,weekly_sales_pct_change
0,1,01-04-2011,1495064.75,NaN,NaN
1,1,01-06-2012,1624477.58,129412.83,0.086560
2,1,01-07-2011,1488538.09,-135939.49,-0.083682
3,1,01-10-2010,1453329.50,-35208.59,-0.023653
4,1,02-03-2012,1688420.76,235091.26,0.161760
...,...,...,...,...,...
6430,45,30-07-2010,716859.27,-20406.30,-0.027678
6431,45,30-09-2011,698986.34,-17872.93,-0.024932
6432,45,30-12-2011,869403.63,170417.29,0.243806
6433,45,31-08-2012,734297.87,-135105.76,-0.155401
6434,45,31-12-2010,679156.20,-55141.67,-0.075094

In [6]:
data = fetch_feature("date_feature.sql",portfolio=portfolio)

In [7]:
data.head()

,store,date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment,month,season,day_of_week,week_of_year,quarter,is_month_start,is_month_end,is_quarter_start,is_quarter_end
0,1,01-04-2011,1495064.75,0,59.17,3.524,214.837166,7.682,4,Spring,5,13,2,1,0,1,0
1,1,01-06-2012,1624477.58,0,77.95,3.501,221.747214,7.143,6,Summer,5,22,2,1,0,0,0
2,1,01-07-2011,1488538.09,0,85.55,3.524,215.184137,7.962,7,Summer,5,26,3,1,0,1,0
3,1,01-10-2010,1453329.50,0,71.89,2.603,211.671989,7.838,10,Autumn,5,39,4,1,0,1,0
4,1,02-03-2012,1688420.76,0,60.96,3.630,220.848045,7.348,3,Spring,5,9,1,0,0,0,0

In [8]:
data = fetch_feature("event_flags.sql",portfolio=portfolio)

In [9]:
data.head()

,store,date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment,super_bowl_flag,labour_day_flag,thanksgiving_flag,christmas_flag
0,1,01-04-2011,1495064.75,0,59.17,3.524,214.837166,7.682,0,0,0,0
1,1,01-06-2012,1624477.58,0,77.95,3.501,221.747214,7.143,0,0,0,0
2,1,01-07-2011,1488538.09,0,85.55,3.524,215.184137,7.962,0,0,0,0
3,1,01-10-2010,1453329.50,0,71.89,2.603,211.671989,7.838,0,0,0,0
4,1,02-03-2012,1688420.76,0,60.96,3.630,220.848045,7.348,0,0,0,0

In [10]:
data = fetch_feature("interaction_features.sql",portfolio=portfolio)

In [11]:
data.head()

,store,date,Fuel_Price,Unemployment,CPI,Temperature,Holiday_Flag,super_bowl_flag,labour_day_flag,thanksgiving_flag,christmas_flag,season,fuel_price_x_unemployment,cpi_x_unemployment,temp_x_season,holiday_x_fuel_price,holiday_x_temperature,total_holidays
0,1,01-04-2011,3.524,7.682,214.837166,59.17,0,0,0,0,0,Spring,27.071368,1650.379112,15.094444,0.0,0.0,0
1,1,01-06-2012,3.501,7.143,221.747214,77.95,0,0,0,0,0,Summer,25.007643,1583.940349,51.055556,0.0,0.0,0
2,1,01-07-2011,3.524,7.962,215.184137,85.55,0,0,0,0,0,Summer,28.058088,1713.296097,59.500000,0.0,0.0,0
3,1,01-10-2010,2.603,7.838,211.671989,71.89,0,0,0,0,0,Autumn,20.402314,1659.085054,66.483333,0.0,0.0,0
4,1,02-03-2012,3.630,7.348,220.848045,60.96,0,0,0,0,0,Spring,26.673240,1622.791438,16.088889,0.0,0.0,0

In [12]:
data = fetch_feature("rolling_features.sql",portfolio=portfolio)

In [13]:
data.head()

,store,date,Weekly_Sales,weekly_sales_rolling_mean_2,weekly_sales_rolling_std_2,weekly_sales_rolling_mean_4,weekly_sales_rolling_std_4
0,1,05-02-2010,1643690.90,1643690.900,NaN,1.643691e+06,NaN
1,1,12-02-2010,1641957.44,1642824.170,1225.741321,1.642824e+06,1225.741321
2,1,19-02-2010,1611968.17,1626962.805,21205.616180,1.632539e+06,17835.791719
3,1,26-02-2010,1409727.59,1510847.880,143005.685549,1.576836e+06,112353.415114
4,1,05-03-2010,1554806.68,1482267.135,102586.408347,1.554615e+06,103135.002548