In [1]:
import sys
import os
import yaml

sys.path.append("..")

with open("../config.yaml", "r") as f:
    config = yaml.safe_load(f)

feature_store_path = config["feature_store_path"]
print("Feature store path:", feature_store_path)

from src.connect import fetch_feature, run_query

Feature store path: C:\Users\o\forcasting\walmart_forcasting\feature_store

In [2]:

query = f"""

SELECT m."Store", m."Date"
FROM walmart AS m

"""

portfolio = run_query(query)

In [3]:
portfolio

      Store        Date
0         1  05-02-2010
1         1  12-02-2010
2         1  19-02-2010
3         1  26-02-2010
4         1  05-03-2010
...     ...         ...
6430     45  28-09-2012
6431     45  05-10-2012
6432     45  12-10-2012
6433     45  19-10-2012
6434     45  26-10-2012

[6435 rows x 2 columns]

In [4]:
data = fetch_feature("growth_features.sql",portfolio=portfolio)

In [5]:
data

,store,date,Weekly_Sales,weekly_sales_diff,weekly_sales_pct_change
0,1,01-04-2011,1495064.75,NaN,NaN
1,1,01-06-2012,1624477.58,129412.83,0.086560
2,1,01-07-2011,1488538.09,-135939.49,-0.083682
3,1,01-10-2010,1453329.50,-35208.59,-0.023653
4,1,02-03-2012,1688420.76,235091.26,0.161760
...,...,...,...,...,...
6430,45,30-07-2010,716859.27,-20406.30,-0.027678
6431,45,30-09-2011,698986.34,-17872.93,-0.024932
6432,45,30-12-2011,869403.63,170417.29,0.243806
6433,45,31-08-2012,734297.87,-135105.76,-0.155401
6434,45,31-12-2010,679156.20,-55141.67,-0.075094

In [6]:
data = fetch_feature("interaction_features.sql",portfolio=portfolio)

Error while executing the query: WITH portfolio(store, date) AS (VALUES (1, '05-02-2010'), (1, '12-02-2010'), (1, '19-02-2010'), (1, '26-02-2010'), (1, '05-03-2010'), (1, '12-03-2010'), (1, '19-03-2010'), (1, '26-03-2010'), (1, '02-04-2010'), (1, '09-04-2010'), (1, '16-04-2010'), (1, '23-04-2010'), (1, '30-04-2010'), (1, '07-05-2010'), (1, '14-05-2010'), (1, '21-05-2010'), (1, '28-05-2010'), (1, '04-06-2010'), (1, '11-06-2010'), (1, '18-06-2010'), (1, '25-06-2010'), (1, '02-07-2010'), (1, '09-07-2010'), (1, '16-07-2010'), (1, '23-07-2010'), (1, '30-07-2010'), (1, '06-08-2010'), (1, '13-08-2010'), (1, '20-08-2010'), (1, '27-08-2010'), (1, '03-09-2010'), (1, '10-09-2010'), (1, '17-09-2010'), (1, '24-09-2010'), (1, '01-10-2010'), (1, '08-10-2010'), (1, '15-10-2010'), (1, '22-10-2010'), (1, '29-10-2010'), (1, '05-11-2010'), (1, '12-11-2010'), (1, '19-11-2010'), (1, '26-11-2010'), (1, '03-12-2010'), (1, '10-12-2010'), (1, '17-12-2010'), (1, '24-12-2010'), (1, '31-12-2010'), (1, '07-01-2011'), (1, '14-01-2011'), (1, '21-01-2011'), (1, '28-01-2011'), (1, '04-02-2011'), (1, '11-02-2011'), (1, '18-02-2011'), (1, '25-02-2011'), (1, '04-03-2011'), (1, '11-03-2011'), (1, '18-03-2011'), (1, '25-03-2011'), (1, '01-04-2011'), (1, '08-04-2011'), (1, '15-04-2011'), (1, '22-04-2011'), (1, '29-04-2011'), (1, '06-05-2011'), (1, '13-05-2011'), (1, '20-05-2011'), (1, '27-05-2011'), (1, '03-06-2011'), (1, '10-06-2011'), (1, '17-06-2011'), (1, '24-06-2011'), (1, '01-07-2011'), (1, '08-07-2011'), (1, '15-07-2011'), (1, '22-07-2011'), (1, '29-07-2011'), (1, '05-08-2011'), (1, '12-08-2011'), (1, '19-08-2011'), (1, '26-08-2011'), (1, '02-09-2011'), (1, '09-09-2011'), (1, '16-09-2011'), (1, '23-09-2011'), (1, '30-09-2011'), (1, '07-10-2011'), (1, '14-10-2011'), (1, '21-10-2011'), (1, '28-10-2011'), (1, '04-11-2011'), (1, '11-11-2011'), (1, '18-11-2011'), (1, '25-11-2011'), (1, '02-12-2011'), (1, '09-12-2011'), (1, '16-12-2011'), (1, '23-12-2011'), (1, '30-12-2011'), (1, '06-01-2012'), (1, '13-01-2012'), (1, '20-01-2012'), (1, '27-01-2012'), (1, '03-02-2012'), (1, '10-02-2012'), (1, '17-02-2012'), (1, '24-02-2012'), (1, '02-03-2012'), (1, '09-03-2012'), (1, '16-03-2012'), (1, '23-03-2012'), (1, '30-03-2012'), (1, '06-04-2012'), (1, '13-04-2012'), (1, '20-04-2012'), (1, '27-04-2012'), (1, '04-05-2012'), (1, '11-05-2012'), (1, '18-05-2012'), (1, '25-05-2012'), (1, '01-06-2012'), (1, '08-06-2012'), (1, '15-06-2012'), (1, '22-06-2012'), (1, '29-06-2012'), (1, '06-07-2012'), (1, '13-07-2012'), (1, '20-07-2012'), (1, '27-07-2012'), (1, '03-08-2012'), (1, '10-08-2012'), (1, '17-08-2012'), (1, '24-08-2012'), (1, '31-08-2012'), (1, '07-09-2012'), (1, '14-09-2012'), (1, '21-09-2012'), (1, '28-09-2012'), (1, '05-10-2012'), (1, '12-10-2012'), (1, '19-10-2012'), (1, '26-10-2012'), (2, '05-02-2010'), (2, '12-02-2010'), (2, '19-02-2010'), (2, '26-02-2010'), (2, '05-03-2010'), (2, '12-03-2010'), (2, '19-03-2010'), (2, '26-03-2010'), (2, '02-04-2010'), (2, '09-04-2010'), (2, '16-04-2010'), (2, '23-04-2010'), (2, '30-04-2010'), (2, '07-05-2010'), (2, '14-05-2010'), (2, '21-05-2010'), (2, '28-05-2010'), (2, '04-06-2010'), (2, '11-06-2010'), (2, '18-06-2010'), (2, '25-06-2010'), (2, '02-07-2010'), (2, '09-07-2010'), (2, '16-07-2010'), (2, '23-07-2010'), (2, '30-07-2010'), (2, '06-08-2010'), (2, '13-08-2010'), (2, '20-08-2010'), (2, '27-08-2010'), (2, '03-09-2010'), (2, '10-09-2010'), (2, '17-09-2010'), (2, '24-09-2010'), (2, '01-10-2010'), (2, '08-10-2010'), (2, '15-10-2010'), (2, '22-10-2010'), (2, '29-10-2010'), (2, '05-11-2010'), (2, '12-11-2010'), (2, '19-11-2010'), (2, '26-11-2010'), (2, '03-12-2010'), (2, '10-12-2010'), (2, '17-12-2010'), (2, '24-12-2010'), (2, '31-12-2010'), (2, '07-01-2011'), (2, '14-01-2011'), (2, '21-01-2011'), (2, '28-01-2011'), (2, '04-02-2011'), (2, '11-02-2011'), (2, '18-02-2011'), (2, '25-02-2011'), (2, '04-03-2011'), (2, '11-03-2011'), (2, '18-03-2011'), (2, '25-03-2011'), (2, '01-04-2011'), (2, '08-04-2011'), (2, '15-04-2011'), (2, '22-04-2011'), (2, '29-04-2011'), (2, '06-05-2011'), (2, '13-05-2011'), (2, '20-05-2011'), (2, '27-05-2011'), (2, '03-06-2011'), (2, '10-06-2011'), (2, '17-06-2011'), (2, '24-06-2011'), (2, '01-07-2011'), (2, '08-07-2011'), (2, '15-07-2011'), (2, '22-07-2011'), (2, '29-07-2011'), (2, '05-08-2011'), (2, '12-08-2011'), (2, '19-08-2011'), (2, '26-08-2011'), (2, '02-09-2011'), (2, '09-09-2011'), (2, '16-09-2011'), (2, '23-09-2011'), (2, '30-09-2011'), (2, '07-10-2011'), (2, '14-10-2011'), (2, '21-10-2011'), (2, '28-10-2011'), (2, '04-11-2011'), (2, '11-11-2011'), (2, '18-11-2011'), (2, '25-11-2011'), (2, '02-12-2011'), (2, '09-12-2011'), (2, '16-12-2011'), (2, '23-12-2011'), (2, '30-12-2011'), (2, '06-01-2012'), (2, '13-01-2012'), (2, '20-01-2012'), (2, '27-01-2012'), (2, '03-02-2012'), (2, '10-02-2012'), (2, '17-02-2012'), (2, '24-02-2012'), (2, '02-03-2012'), (2, '09-03-2012'), (2, '16-03-2012'), (2, '23-03-2012'), (2, '30-03-2012'), (2, '06-04-2012'), (2, '13-04-2012'), (2, '20-04-2012'), (2, '27-04-2012'), (2, '04-05-2012'), (2, '11-05-2012'), (2, '18-05-2012'), (2, '25-05-2012'), (2, '01-06-2012'), (2, '08-06-2012'), (2, '15-06-2012'), (2, '22-06-2012'), (2, '29-06-2012'), (2, '06-07-2012'), (2, '13-07-2012'), (2, '20-07-2012'), (2, '27-07-2012'), (2, '03-08-2012'), (2, '10-08-2012'), (2, '17-08-2012'), (2, '24-08-2012'), (2, '31-08-2012'), (2, '07-09-2012'), (2, '14-09-2012'), (2, '21-09-2012'), (2, '28-09-2012'), (2, '05-10-2012'), (2, '12-10-2012'), (2, '19-10-2012'), (2, '26-10-2012'), (3, '05-02-2010'), (3, '12-02-2010'), (3, '19-02-2010'), (3, '26-02-2010'), (3, '05-03-2010'), (3, '12-03-2010'), (3, '19-03-2010'), (3, '26-03-2010'), (3, '02-04-2010'), (3, '09-04-2010'), (3, '16-04-2010'), (3, '23-04-2010'), (3, '30-04-2010'), (3, '07-05-2010'), (3, '14-05-2010'), (3, '21-05-2010'), (3, '28-05-2010'), (3, '04-06-2010'), (3, '11-06-2010'), (3, '18-06-2010'), (3, '25-06-2010'), (3, '02-07-2010'), (3, '09-07-2010'), (3, '16-07-2010'), (3, '23-07-2010'), (3, '30-07-2010'), (3, '06-08-2010'), (3, '13-08-2010'), (3, '20-08-2010'), (3, '27-08-2010'), (3, '03-09-2010'), (3, '10-09-2010'), (3, '17-09-2010'), (3, '24-09-2010'), (3, '01-10-2010'), (3, '08-10-2010'), (3, '15-10-2010'), (3, '22-10-2010'), (3, '29-10-2010'), (3, '05-11-2010'), (3, '12-11-2010'), (3, '19-11-2010'), (3, '26-11-2010'), (3, '03-12-2010'), (3, '10-12-2010'), (3, '17-12-2010'), (3, '24-12-2010'), (3, '31-12-2010'), (3, '07-01-2011'), (3, '14-01-2011'), (3, '21-01-2011'), (3, '28-01-2011'), (3, '04-02-2011'), (3, '11-02-2011'), (3, '18-02-2011'), (3, '25-02-2011'), (3, '04-03-2011'), (3, '11-03-2011'), (3, '18-03-2011'), (3, '25-03-2011'), (3, '01-04-2011'), (3, '08-04-2011'), (3, '15-04-2011'), (3, '22-04-2011'), (3, '29-04-2011'), (3, '06-05-2011'), (3, '13-05-2011'), (3, '20-05-2011'), (3, '27-05-2011'), (3, '03-06-2011'), (3, '10-06-2011'), (3, '17-06-2011'), (3, '24-06-2011'), (3, '01-07-2011'), (3, '08-07-2011'), (3, '15-07-2011'), (3, '22-07-2011'), (3, '29-07-2011'), (3, '05-08-2011'), (3, '12-08-2011'), (3, '19-08-2011'), (3, '26-08-2011'), (3, '02-09-2011'), (3, '09-09-2011'), (3, '16-09-2011'), (3, '23-09-2011'), (3, '30-09-2011'), (3, '07-10-2011'), (3, '14-10-2011'), (3, '21-10-2011'), (3, '28-10-2011'), (3, '04-11-2011'), (3, '11-11-2011'), (3, '18-11-2011'), (3, '25-11-2011'), (3, '02-12-2011'), (3, '09-12-2011'), (3, '16-12-2011'), (3, '23-12-2011'), (3, '30-12-2011'), (3, '06-01-2012'), (3, '13-01-2012'), (3, '20-01-2012'), (3, '27-01-2012'), (3, '03-02-2012'), (3, '10-02-2012'), (3, '17-02-2012'), (3, '24-02-2012'), (3, '02-03-2012'), (3, '09-03-2012'), (3, '16-03-2012'), (3, '23-03-2012'), (3, '30-03-2012'), (3, '06-04-2012'), (3, '13-04-2012'), (3, '20-04-2012'), (3, '27-04-2012'), (3, '04-05-2012'), (3, '11-05-2012'), (3, '18-05-2012'), (3, '25-05-2012'), (3, '01-06-2012'), (3, '08-06-2012'), (3, '15-06-2012'), (3, '22-06-2012'), (3, '29-06-2012'), (3, '06-07-2012'), (3, '13-07-2012'), (3, '20-07-2012'), (3, '27-07-2012'), (3, '03-08-2012'), (3, '10-08-2012'), (3, '17-08-2012'), (3, '24-08-2012'), (3, '31-08-2012'), (3, '07-09-2012'), (3, '14-09-2012'), (3, '21-09-2012'), (3, '28-09-2012'), (3, '05-10-2012'), (3, '12-10-2012'), (3, '19-10-2012'), (3, '26-10-2012'), (4, '05-02-2010'), (4, '12-02-2010'), (4, '19-02-2010'), (4, '26-02-2010'), (4, '05-03-2010'), (4, '12-03-2010'), (4, '19-03-2010'), (4, '26-03-2010'), (4, '02-04-2010'), (4, '09-04-2010'), (4, '16-04-2010'), (4, '23-04-2010'), (4, '30-04-2010'), (4, '07-05-2010'), (4, '14-05-2010'), (4, '21-05-2010'), (4, '28-05-2010'), (4, '04-06-2010'), (4, '11-06-2010'), (4, '18-06-2010'), (4, '25-06-2010'), (4, '02-07-2010'), (4, '09-07-2010'), (4, '16-07-2010'), (4, '23-07-2010'), (4, '30-07-2010'), (4, '06-08-2010'), (4, '13-08-2010'), (4, '20-08-2010'), (4, '27-08-2010'), (4, '03-09-2010'), (4, '10-09-2010'), (4, '17-09-2010'), (4, '24-09-2010'), (4, '01-10-2010'), (4, '08-10-2010'), (4, '15-10-2010'), (4, '22-10-2010'), (4, '29-10-2010'), (4, '05-11-2010'), (4, '12-11-2010'), (4, '19-11-2010'), (4, '26-11-2010'), (4, '03-12-2010'), (4, '10-12-2010'), (4, '17-12-2010'), (4, '24-12-2010'), (4, '31-12-2010'), (4, '07-01-2011'), (4, '14-01-2011'), (4, '21-01-2011'), (4, '28-01-2011'), (4, '04-02-2011'), (4, '11-02-2011'), (4, '18-02-2011'), (4, '25-02-2011'), (4, '04-03-2011'), (4, '11-03-2011'), (4, '18-03-2011'), (4, '25-03-2011'), (4, '01-04-2011'), (4, '08-04-2011'), (4, '15-04-2011'), (4, '22-04-2011'), (4, '29-04-2011'), (4, '06-05-2011'), (4, '13-05-2011'), (4, '20-05-2011'), (4, '27-05-2011'), (4, '03-06-2011'), (4, '10-06-2011'), (4, '17-06-2011'), (4, '24-06-2011'), (4, '01-07-2011'), (4, '08-07-2011'), (4, '15-07-2011'), (4, '22-07-2011'), (4, '29-07-2011'), (4, '05-08-2011'), (4, '12-08-2011'), (4, '19-08-2011'), (4, '26-08-2011'), (4, '02-09-2011'), (4, '09-09-2011'), (4, '16-09-2011'), (4, '23-09-2011'), (4, '30-09-2011'), (4, '07-10-2011'), (4, '14-10-2011'), (4, '21-10-2011'), (4, '28-10-2011'), (4, '04-11-2011'), (4, '11-11-2011'), (4, '18-11-2011'), (4, '25-11-2011'), (4, '02-12-2011'), (4, '09-12-2011'), (4, '16-12-2011'), (4, '23-12-2011'), (4, '30-12-2011'), (4, '06-01-2012'), (4, '13-01-2012'), (4, '20-01-2012'), (4, '27-01-2012'), (4, '03-02-2012'), (4, '10-02-2012'), (4, '17-02-2012'), (4, '24-02-2012'), (4, '02-03-2012'), (4, '09-03-2012'), (4, '16-03-2012'), (4, '23-03-2012'), (4, '30-03-2012'), (4, '06-04-2012'), (4, '13-04-2012'), (4, '20-04-2012'), (4, '27-04-2012'), (4, '04-05-2012'), (4, '11-05-2012'), (4, '18-05-2012'), (4, '25-05-2012'), (4, '01-06-2012'), (4, '08-06-2012'), (4, '15-06-2012'), (4, '22-06-2012'), (4, '29-06-2012'), (4, '06-07-2012'), (4, '13-07-2012'), (4, '20-07-2012'), (4, '27-07-2012'), (4, '03-08-2012'), (4, '10-08-2012'), (4, '17-08-2012'), (4, '24-08-2012'), (4, '31-08-2012'), (4, '07-09-2012'), (4, '14-09-2012'), (4, '21-09-2012'), (4, '28-09-2012'), (4, '05-10-2012'), (4, '12-10-2012'), (4, '19-10-2012'), (4, '26-10-2012'), (5, '05-02-2010'), (5, '12-02-2010'), (5, '19-02-2010'), (5, '26-02-2010'), (5, '05-03-2010'), (5, '12-03-2010'), (5, '19-03-2010'), (5, '26-03-2010'), (5, '02-04-2010'), (5, '09-04-2010'), (5, '16-04-2010'), (5, '23-04-2010'), (5, '30-04-2010'), (5, '07-05-2010'), (5, '14-05-2010'), (5, '21-05-2010'), (5, '28-05-2010'), (5, '04-06-2010'), (5, '11-06-2010'), (5, '18-06-2010'), (5, '25-06-2010'), (5, '02-07-2010'), (5, '09-07-2010'), (5, '16-07-2010'), (5, '23-07-2010'), (5, '30-07-2010'), (5, '06-08-2010'), (5, '13-08-2010'), (5, '20-08-2010'), (5, '27-08-2010'), (5, '03-09-2010'), (5, '10-09-2010'), (5, '17-09-2010'), (5, '24-09-2010'), (5, '01-10-2010'), (5, '08-10-2010'), (5, '15-10-2010'), (5, '22-10-2010'), (5, '29-10-2010'), (5, '05-11-2010'), (5, '12-11-2010'), (5, '19-11-2010'), (5, '26-11-2010'), (5, '03-12-2010'), (5, '10-12-2010'), (5, '17-12-2010'), (5, '24-12-2010'), (5, '31-12-2010'), (5, '07-01-2011'), (5, '14-01-2011'), (5, '21-01-2011'), (5, '28-01-2011'), (5, '04-02-2011'), (5, '11-02-2011'), (5, '18-02-2011'), (5, '25-02-2011'), (5, '04-03-2011'), (5, '11-03-2011'), (5, '18-03-2011'), (5, '25-03-2011'), (5, '01-04-2011'), (5, '08-04-2011'), (5, '15-04-2011'), (5, '22-04-2011'), (5, '29-04-2011'), (5, '06-05-2011'), (5, '13-05-2011'), (5, '20-05-2011'), (5, '27-05-2011'), (5, '03-06-2011'), (5, '10-06-2011'), (5, '17-06-2011'), (5, '24-06-2011'), (5, '01-07-2011'), (5, '08-07-2011'), (5, '15-07-2011'), (5, '22-07-2011'), (5, '29-07-2011'), (5, '05-08-2011'), (5, '12-08-2011'), (5, '19-08-2011'), (5, '26-08-2011'), (5, '02-09-2011'), (5, '09-09-2011'), (5, '16-09-2011'), (5, '23-09-2011'), (5, '30-09-2011'), (5, '07-10-2011'), (5, '14-10-2011'), (5, '21-10-2011'), (5, '28-10-2011'), (5, '04-11-2011'), (5, '11-11-2011'), (5, '18-11-2011'), (5, '25-11-2011'), (5, '02-12-2011'), (5, '09-12-2011'), (5, '16-12-2011'), (5, '23-12-2011'), (5, '30-12-2011'), (5, '06-01-2012'), (5, '13-01-2012'), (5, '20-01-2012'), (5, '27-01-2012'), (5, '03-02-2012'), (5, '10-02-2012'), (5, '17-02-2012'), (5, '24-02-2012'), (5, '02-03-2012'), (5, '09-03-2012'), (5, '16-03-2012'), (5, '23-03-2012'), (5, '30-03-2012'), (5, '06-04-2012'), (5, '13-04-2012'), (5, '20-04-2012'), (5, '27-04-2012'), (5, '04-05-2012'), (5, '11-05-2012'), (5, '18-05-2012'), (5, '25-05-2012'), (5, '01-06-2012'), (5, '08-06-2012'), (5, '15-06-2012'), (5, '22-06-2012'), (5, '29-06-2012'), (5, '06-07-2012'), (5, '13-07-2012'), (5, '20-07-2012'), (5, '27-07-2012'), (5, '03-08-2012'), (5, '10-08-2012'), (5, '17-08-2012'), (5, '24-08-2012'), (5, '31-08-2012'), (5, '07-09-2012'), (5, '14-09-2012'), (5, '21-09-2012'), (5, '28-09-2012'), (5, '05-10-2012'), (5, '12-10-2012'), (5, '19-10-2012'), (5, '26-10-2012'), (6, '05-02-2010'), (6, '12-02-2010'), (6, '19-02-2010'), (6, '26-02-2010'), (6, '05-03-2010'), (6, '12-03-2010'), (6, '19-03-2010'), (6, '26-03-2010'), (6, '02-04-2010'), (6, '09-04-2010'), (6, '16-04-2010'), (6, '23-04-2010'), (6, '30-04-2010'), (6, '07-05-2010'), (6, '14-05-2010'), (6, '21-05-2010'), (6, '28-05-2010'), (6, '04-06-2010'), (6, '11-06-2010'), (6, '18-06-2010'), (6, '25-06-2010'), (6, '02-07-2010'), (6, '09-07-2010'), (6, '16-07-2010'), (6, '23-07-2010'), (6, '30-07-2010'), (6, '06-08-2010'), (6, '13-08-2010'), (6, '20-08-2010'), (6, '27-08-2010'), (6, '03-09-2010'), (6, '10-09-2010'), (6, '17-09-2010'), (6, '24-09-2010'), (6, '01-10-2010'), (6, '08-10-2010'), (6, '15-10-2010'), (6, '22-10-2010'), (6, '29-10-2010'), (6, '05-11-2010'), (6, '12-11-2010'), (6, '19-11-2010'), (6, '26-11-2010'), (6, '03-12-2010'), (6, '10-12-2010'), (6, '17-12-2010'), (6, '24-12-2010'), (6, '31-12-2010'), (6, '07-01-2011'), (6, '14-01-2011'), (6, '21-01-2011'), (6, '28-01-2011'), (6, '04-02-2011'), (6, '11-02-2011'), (6, '18-02-2011'), (6, '25-02-2011'), (6, '04-03-2011'), (6, '11-03-2011'), (6, '18-03-2011'), (6, '25-03-2011'), (6, '01-04-2011'), (6, '08-04-2011'), (6, '15-04-2011'), (6, '22-04-2011'), (6, '29-04-2011'), (6, '06-05-2011'), (6, '13-05-2011'), (6, '20-05-2011'), (6, '27-05-2011'), (6, '03-06-2011'), (6, '10-06-2011'), (6, '17-06-2011'), (6, '24-06-2011'), (6, '01-07-2011'), (6, '08-07-2011'), (6, '15-07-2011'), (6, '22-07-2011'), (6, '29-07-2011'), (6, '05-08-2011'), (6, '12-08-2011'), (6, '19-08-2011'), (6, '26-08-2011'), (6, '02-09-2011'), (6, '09-09-2011'), (6, '16-09-2011'), (6, '23-09-2011'), (6, '30-09-2011'), (6, '07-10-2011'), (6, '14-10-2011'), (6, '21-10-2011'), (6, '28-10-2011'), (6, '04-11-2011'), (6, '11-11-2011'), (6, '18-11-2011'), (6, '25-11-2011'), (6, '02-12-2011'), (6, '09-12-2011'), (6, '16-12-2011'), (6, '23-12-2011'), (6, '30-12-2011'), (6, '06-01-2012'), (6, '13-01-2012'), (6, '20-01-2012'), (6, '27-01-2012'), (6, '03-02-2012'), (6, '10-02-2012'), (6, '17-02-2012'), (6, '24-02-2012'), (6, '02-03-2012'), (6, '09-03-2012'), (6, '16-03-2012'), (6, '23-03-2012'), (6, '30-03-2012'), (6, '06-04-2012'), (6, '13-04-2012'), (6, '20-04-2012'), (6, '27-04-2012'), (6, '04-05-2012'), (6, '11-05-2012'), (6, '18-05-2012'), (6, '25-05-2012'), (6, '01-06-2012'), (6, '08-06-2012'), (6, '15-06-2012'), (6, '22-06-2012'), (6, '29-06-2012'), (6, '06-07-2012'), (6, '13-07-2012'), (6, '20-07-2012'), (6, '27-07-2012'), (6, '03-08-2012'), (6, '10-08-2012'), (6, '17-08-2012'), (6, '24-08-2012'), (6, '31-08-2012'), (6, '07-09-2012'), (6, '14-09-2012'), (6, '21-09-2012'), (6, '28-09-2012'), (6, '05-10-2012'), (6, '12-10-2012'), (6, '19-10-2012'), (6, '26-10-2012'), (7, '05-02-2010'), (7, '12-02-2010'), (7, '19-02-2010'), (7, '26-02-2010'), (7, '05-03-2010'), (7, '12-03-2010'), (7, '19-03-2010'), (7, '26-03-2010'), (7, '02-04-2010'), (7, '09-04-2010'), (7, '16-04-2010'), (7, '23-04-2010'), (7, '30-04-2010'), (7, '07-05-2010'), (7, '14-05-2010'), (7, '21-05-2010'), (7, '28-05-2010'), (7, '04-06-2010'), (7, '11-06-2010'), (7, '18-06-2010'), (7, '25-06-2010'), (7, '02-07-2010'), (7, '09-07-2010'), (7, '16-07-2010'), (7, '23-07-2010'), (7, '30-07-2010'), (7, '06-08-2010'), (7, '13-08-2010'), (7, '20-08-2010'), (7, '27-08-2010'), (7, '03-09-2010'), (7, '10-09-2010'), (7, '17-09-2010'), (7, '24-09-2010'), (7, '01-10-2010'), (7, '08-10-2010'), (7, '15-10-2010'), (7, '22-10-2010'), (7, '29-10-2010'), (7, '05-11-2010'), (7, '12-11-2010'), (7, '19-11-2010'), (7, '26-11-2010'), (7, '03-12-2010'), (7, '10-12-2010'), (7, '17-12-2010'), (7, '24-12-2010'), (7, '31-12-2010'), (7, '07-01-2011'), (7, '14-01-2011'), (7, '21-01-2011'), (7, '28-01-2011'), (7, '04-02-2011'), (7, '11-02-2011'), (7, '18-02-2011'), (7, '25-02-2011'), (7, '04-03-2011'), (7, '11-03-2011'), (7, '18-03-2011'), (7, '25-03-2011'), (7, '01-04-2011'), (7, '08-04-2011'), (7, '15-04-2011'), (7, '22-04-2011'), (7, '29-04-2011'), (7, '06-05-2011'), (7, '13-05-2011'), (7, '20-05-2011'), (7, '27-05-2011'), (7, '03-06-2011'), (7, '10-06-2011'), (7, '17-06-2011'), (7, '24-06-2011'), (7, '01-07-2011'), (7, '08-07-2011'), (7, '15-07-2011'), (7, '22-07-2011'), (7, '29-07-2011'), (7, '05-08-2011'), (7, '12-08-2011'), (7, '19-08-2011'), (7, '26-08-2011'), (7, '02-09-2011'), (7, '09-09-2011'), (7, '16-09-2011'), (7, '23-09-2011'), (7, '30-09-2011'), (7, '07-10-2011'), (7, '14-10-2011'), (7, '21-10-2011'), (7, '28-10-2011'), (7, '04-11-2011'), (7, '11-11-2011'), (7, '18-11-2011'), (7, '25-11-2011'), (7, '02-12-2011'), (7, '09-12-2011'), (7, '16-12-2011'), (7, '23-12-2011'), (7, '30-12-2011'), (7, '06-01-2012'), (7, '13-01-2012'), (7, '20-01-2012'), (7, '27-01-2012'), (7, '03-02-2012'), (7, '10-02-2012'), (7, '17-02-2012'), (7, '24-02-2012'), (7, '02-03-2012'), (7, '09-03-2012'), (7, '16-03-2012'), (7, '23-03-2012'), (7, '30-03-2012'), (7, '06-04-2012'), (7, '13-04-2012'), (7, '20-04-2012'), (7, '27-04-2012'), (7, '04-05-2012'), (7, '11-05-2012'), (7, '18-05-2012'), (7, '25-05-2012'), (7, '01-06-2012'), (7, '08-06-2012'), (7, '15-06-2012'), (7, '22-06-2012'), (7, '29-06-2012'), (7, '06-07-2012'), (7, '13-07-2012'), (7, '20-07-2012'), (7, '27-07-2012'), (7, '03-08-2012'), (7, '10-08-2012'), (7, '17-08-2012'), (7, '24-08-2012'), (7, '31-08-2012'), (7, '07-09-2012'), (7, '14-09-2012'), (7, '21-09-2012'), (7, '28-09-2012'), (7, '05-10-2012'), (7, '12-10-2012'), (7, '19-10-2012'), (7, '26-10-2012'), (8, '05-02-2010'), (8, '12-02-2010'), (8, '19-02-2010'), (8, '26-02-2010'), (8, '05-03-2010'), (8, '12-03-2010'), (8, '19-03-2010'), (8, '26-03-2010'), (8, '02-04-2010'), (8, '09-04-2010'), (8, '16-04-2010'), (8, '23-04-2010'), (8, '30-04-2010'), (8, '07-05-2010'), (8, '14-05-2010'), (8, '21-05-2010'), (8, '28-05-2010'), (8, '04-06-2010'), (8, '11-06-2010'), (8, '18-06-2010'), (8, '25-06-2010'), (8, '02-07-2010'), (8, '09-07-2010'), (8, '16-07-2010'), (8, '23-07-2010'), (8, '30-07-2010'), (8, '06-08-2010'), (8, '13-08-2010'), (8, '20-08-2010'), (8, '27-08-2010'), (8, '03-09-2010'), (8, '10-09-2010'), (8, '17-09-2010'), (8, '24-09-2010'), (8, '01-10-2010'), (8, '08-10-2010'), (8, '15-10-2010'), (8, '22-10-2010'), (8, '29-10-2010'), (8, '05-11-2010'), (8, '12-11-2010'), (8, '19-11-2010'), (8, '26-11-2010'), (8, '03-12-2010'), (8, '10-12-2010'), (8, '17-12-2010'), (8, '24-12-2010'), (8, '31-12-2010'